web_app:
  context_path: "turan"
  mode: "dev"
  host: "127.0.0.1"
  port: 8081

log:
  level: "info"
  fileName: "turan.log"
  path: "./log/"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "go_web_demo"
  user: "root"
  password: "123456"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100

